name: flutter_weather
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_google_places_sdk: ^0.4.2+1
  flutter_localizations:
    sdk: flutter
  geolocator: ^14.0.1
  go_router: ^15.2.3
  internet_connection_checker: ^3.0.1
  intl: ^0.20.2
  lottie: ^3.3.1
  permission_handler: ^12.0.0+1
  shared_preferences: ^2.5.3
  weather_repository:
    path: packages/weather_repository
  weather_ui:
    path: packages/weather_ui

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
